apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: container-template-example-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["Hello from Container Template!"]
