apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-template-example-
spec:
  entrypoint: steps-example
  templates:
  - name: steps-example
    steps:
    - - name: step-1
        template: whalesay
    - - name: step-2
        template: whalesay
    - - name: step-3
        template: whalesay
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["Hello from {{name}}!"]
